/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as CheckoutResultRouteImport } from './routes/checkout/result'
import { Route as InsightsIndexRouteImport } from './routes/insights/index'
import { Route as InsightsSlugRouteImport } from './routes/insights/$slug'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesSlugRouteImport } from './routes/services/$slug'
import { Route as AdminCategoriesIndexRouteImport } from './routes/admin/categories/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers/index'
import { Route as AdminMessagesIndexRouteImport } from './routes/admin/messages/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminPostsIndexRouteImport } from './routes/admin/posts/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin/projects/index'
import { Route as AdminRewardsIndexRouteImport } from './routes/admin/rewards/index'
import { Route as AdminRolesIndexRouteImport } from './routes/admin/roles/index'
import { Route as AdminServicesIndexRouteImport } from './routes/admin/services/index'
import { Route as ApiPublicPesapalIpnRouteImport } from './routes/api/public/pesapal/ipn'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutResultRoute = CheckoutResultRouteImport.update({
  id: '/checkout/result',
  path: '/checkout/result',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesIndexRoute = AdminCategoriesIndexRouteImport.update({
  id: '/admin/categories/',
  path: '/admin/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/admin/customers/',
  path: '/admin/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesIndexRoute = AdminMessagesIndexRouteImport.update({
  id: '/admin/messages/',
  path: '/admin/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPostsIndexRoute = AdminPostsIndexRouteImport.update({
  id: '/admin/posts/',
  path: '/admin/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/admin/projects/',
  path: '/admin/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRewardsIndexRoute = AdminRewardsIndexRouteImport.update({
  id: '/admin/rewards/',
  path: '/admin/rewards/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesIndexRoute = AdminRolesIndexRouteImport.update({
  id: '/admin/roles/',
  path: '/admin/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/admin/services/',
  path: '/admin/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPesapalIpnRoute = ApiPublicPesapalIpnRouteImport.update({
  id: '/api/public/pesapal/ipn',
  path: '/api/public/pesapal/ipn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/checkout/result': typeof CheckoutResultRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/messages/': typeof AdminMessagesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/rewards/': typeof AdminRewardsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/checkout/result': typeof CheckoutResultRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/insights': typeof InsightsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/admin/categories': typeof AdminCategoriesIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/messages': typeof AdminMessagesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/posts': typeof AdminPostsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/rewards': typeof AdminRewardsIndexRoute
  '/admin/roles': typeof AdminRolesIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/checkout/result': typeof CheckoutResultRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/insights/': typeof InsightsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/admin/categories/': typeof AdminCategoriesIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/messages/': typeof AdminMessagesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/posts/': typeof AdminPostsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/rewards/': typeof AdminRewardsIndexRoute
  '/admin/roles/': typeof AdminRolesIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/api/public/pesapal/ipn': typeof ApiPublicPesapalIpnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/checkout/result'
    | '/insights/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/account/'
    | '/admin/'
    | '/checkout/'
    | '/insights/'
    | '/products/'
    | '/projects/'
    | '/services/'
    | '/admin/categories/'
    | '/admin/customers/'
    | '/admin/messages/'
    | '/admin/orders/'
    | '/admin/posts/'
    | '/admin/products/'
    | '/admin/projects/'
    | '/admin/rewards/'
    | '/admin/roles/'
    | '/admin/services/'
    | '/api/public/pesapal/ipn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/checkout/result'
    | '/insights/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/insights'
    | '/products'
    | '/projects'
    | '/services'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/posts'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/rewards'
    | '/admin/roles'
    | '/admin/services'
    | '/api/public/pesapal/ipn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/contact'
    | '/checkout/result'
    | '/insights/$slug'
    | '/products/$slug'
    | '/projects/$slug'
    | '/services/$slug'
    | '/account/'
    | '/admin/'
    | '/checkout/'
    | '/insights/'
    | '/products/'
    | '/projects/'
    | '/services/'
    | '/admin/categories/'
    | '/admin/customers/'
    | '/admin/messages/'
    | '/admin/orders/'
    | '/admin/posts/'
    | '/admin/products/'
    | '/admin/projects/'
    | '/admin/rewards/'
    | '/admin/roles/'
    | '/admin/services/'
    | '/api/public/pesapal/ipn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  CheckoutResultRoute: typeof CheckoutResultRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  AdminCategoriesIndexRoute: typeof AdminCategoriesIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminMessagesIndexRoute: typeof AdminMessagesIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPostsIndexRoute: typeof AdminPostsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminRewardsIndexRoute: typeof AdminRewardsIndexRoute
  AdminRolesIndexRoute: typeof AdminRolesIndexRoute
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
  ApiPublicPesapalIpnRoute: typeof ApiPublicPesapalIpnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/result': {
      id: '/checkout/result'
      path: '/checkout/result'
      fullPath: '/checkout/result'
      preLoaderRoute: typeof CheckoutResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories/': {
      id: '/admin/categories/'
      path: '/admin/categories'
      fullPath: '/admin/categories/'
      preLoaderRoute: typeof AdminCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers/': {
      id: '/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages/': {
      id: '/admin/messages/'
      path: '/admin/messages'
      fullPath: '/admin/messages/'
      preLoaderRoute: typeof AdminMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/posts/': {
      id: '/admin/posts/'
      path: '/admin/posts'
      fullPath: '/admin/posts/'
      preLoaderRoute: typeof AdminPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/admin/projects'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rewards/': {
      id: '/admin/rewards/'
      path: '/admin/rewards'
      fullPath: '/admin/rewards/'
      preLoaderRoute: typeof AdminRewardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles/': {
      id: '/admin/roles/'
      path: '/admin/roles'
      fullPath: '/admin/roles/'
      preLoaderRoute: typeof AdminRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/admin/services'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pesapal/ipn': {
      id: '/api/public/pesapal/ipn'
      path: '/api/public/pesapal/ipn'
      fullPath: '/api/public/pesapal/ipn'
      preLoaderRoute: typeof ApiPublicPesapalIpnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  CheckoutResultRoute: CheckoutResultRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  AdminCategoriesIndexRoute: AdminCategoriesIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminMessagesIndexRoute: AdminMessagesIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPostsIndexRoute: AdminPostsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminRewardsIndexRoute: AdminRewardsIndexRoute,
  AdminRolesIndexRoute: AdminRolesIndexRoute,
  AdminServicesIndexRoute: AdminServicesIndexRoute,
  ApiPublicPesapalIpnRoute: ApiPublicPesapalIpnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
